### ISSUE TITLE
Cant chat

### ISSUE THREAD

**Issue by wcoleman320** [geNAZt/CloudChat#86]
I had CC working then i updated, and now it says, "you cant write in this channal". I checked all my perms, i just cant figure out whats wrong

**Comment by ravand1990** [comment]
Give yourself or the default rank the permission and negate cloudchat.cannot.write.*

**Comment by geNAZt** [comment]
Permissions
▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬ ▬
​
"Help! I'm OP and unable to chat in any channel, but my players can chat!"
In order to fix this problem, you need to negate a permission. Open up your permission file and add the following line,
- \- -cloudchat.cannot.write.*
  The extra - tells PermissionsEx to negate that permission, so be sure to check with your permission plugin to be sure you are using the correct format to negate permissions. Then upload the new file, refresh the plugin, and re-log into your server. The problem should be fixed!

http://www.spigotmc.org/resources/cloudchat.266/
